# Generated by Django 5.0.3 on 2024-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=20)),
                ('KM_price', models.IntegerField()),
                ('road_no', models.IntegerField()),
                ('maintaince_price', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('ON', 'ONLINE PAYMENT'), ('EMI', 'MONTHLY INSTALLMENT')], max_length=10)),
                ('road_length', models.CharField(choices=[('2KM', '2000m'), ('3KM', '3000m'), ('4KM', '4000m')], max_length=10)),
            ],
        ),
    ]
